Repository BlackCubes/covidmap-react-native, pull requests merged in 2021-10, with the labels that each got.

#8 Redux Toolkit Setup
  covid-mapper/App.js
  covid-mapper/api/covidApi.js
  covid-mapper/package-lock.json
  covid-mapper/package.json
  covid-mapper/store.js
  covid-mapper/yarn.lock
Labels: enhancement

#10 Retrieve Worldometers, John Hopkins, and Vaccine Endpoints from Disease.sh
  covid-mapper/api/covidApi.js
Labels: enhancement

#12 Serializable Check to False
  covid-mapper/store.js
Labels: bug

#17 Create Menubar
  covid-mapper/features/map-layout/components/MenuBar.js
Labels: enhancement

#18 Finish Drawer Navigation setup.
  covid-mapper/features/drawer/DrawerContent.js
  covid-mapper/features/drawer/DrawerMenu.js
  covid-mapper/package-lock.json
  covid-mapper/package.json
  covid-mapper/yarn.lock
Labels: enhancement

#28 Map Component and Map Layout
  covid-mapper/features/drawer/DrawerMenu.js
  covid-mapper/features/map-layout/MapLayout.js
  covid-mapper/features/map-layout/components/DrawerButton.js
  covid-mapper/features/map/Map.js
  covid-mapper/features/searchbar/Searchbar.js
Labels: enhancement

#37 Installed 'he' package to decode HTML entities
  covid-mapper/features/vaccine-layout/components/VaccineItem.js
  covid-mapper/package-lock.json
  covid-mapper/package.json
  covid-mapper/yarn.lock
Labels: enhancement

#39 feat(covid-mapper): add Spinner component with react native's Activit…
  covid-mapper/commons/components/Spinner/Spinner.js
  covid-mapper/features/vaccine-layout/VaccineLayout.js
Labels: enhancement

#45 Fix some of the query param in `covidApi.js` for more than two
  covid-mapper/api/covidApi.js
  covid-mapper/features/map-layout/MapLayout.js
Labels: bug

#47 Removed input string after submission
  covid-mapper/features/searchbar/Searchbar.js
Labels: bug

#51 Made search bar icon simulate as a button
  covid-mapper/features/searchbar/Searchbar.js
Labels: enhancement

#61 Display Countries And Provinces in Popup Slider
  covid-mapper/babel.config.js
  covid-mapper/features/map-layout/MapLayout.js
  covid-mapper/features/map-layout/components/PopupSlider.js
  covid-mapper/package-lock.json
  covid-mapper/package.json
  covid-mapper/yarn.lock
Labels: bug, enhancement

#112 Capitalize Function
  covid-mapper/api/covidApi.js
  covid-mapper/features/map-layout/components/PopupSlider.js
  covid-mapper/utils/capitalize.js
  covid-mapper/utils/index.js
Labels: enhancement

#114 Graph Label and Style
  covid-mapper/features/graphs/TimeLineGraph.js
  covid-mapper/utils/numSeparator.js
Labels: enhancement

#115 Expanded Covid API data output to include property for US State name
  covid-mapper/api/covidApi.js
  covid-mapper/features/map-layout/components/PopupSlider.js
Labels: enhancement

#118 Add expo google fonts in VaccineItem and Drawer
  covid-mapper/features/drawer/DrawerMenu.js
  covid-mapper/features/drawer/components/MainContent.js
  covid-mapper/features/drawer/components/ios/IOSLogoSection.js
  covid-mapper/features/graphs/TimeLineGraph.js
  covid-mapper/features/vaccine-layout/VaccineLayout.js
  covid-mapper/features/vaccine-layout/components/VaccineItem.js
  covid-mapper/package-lock.json
  covid-mapper/package.json
  covid-mapper/yarn.lock
Labels: enhancement

#119 Searchbar and PreviousRegion Button Position
  covid-mapper/commons/components/FloatingSearchButton/FloatingSearchButton.js
  covid-mapper/commons/components/PreviousRegionButton/PreviousRegionButton.js
  covid-mapper/commons/components/PreviousRegionButton/styles.js
  covid-mapper/features/searchbar/Searchbar.js
Labels: enhancement

#120 Add onPressOut to call Keyboard.dismiss()
  covid-mapper/features/map-layout/MapLayout.js
Labels: enhancement

#122 Refactor Slider
  covid-mapper/features/map-layout/MapLayout.js
  covid-mapper/features/map-layout/components/PopupSlider.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSlider.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js
  covid-mapper/features/map-layout/components/popup-slider/index.js
Labels: enhancement

#124 Eg 121 population date properties
  covid-mapper/api/covidApi.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSlider.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js
Labels: enhancement
