Repository BlackCubes/covidmap-react-native, pull requests merged in 2021-11, with the labels that each got.

#130 Fixed US Counties Bug
  covid-mapper/features/map-layout/MapLayout.js
  covid-mapper/utils/index.js
  covid-mapper/utils/retrieveCountyData.js
Labels: bug

#132 Change search input to lowercase in handleSearchSubmit
  covid-mapper/features/searchbar/Searchbar.js
Labels: enhancement

#134 Add Pins
  covid-mapper/features/map-layout/MapLayout.js
  covid-mapper/features/map/Map.js
Labels: enhancement

#135 Refactored Slider Functionalities
  covid-mapper/commons/components/ErrorModal/ErrorModal.js
  covid-mapper/commons/components/ErrorModal/index.js
  covid-mapper/commons/components/ErrorModal/styles.js
  covid-mapper/features/map-layout/MapLayout.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSlider.js
  covid-mapper/features/searchbar/Searchbar.js
Labels: bug, enhancement

#147 Refactored `MapLayout`
  covid-mapper/features/drawer/DrawerMenu.js
  covid-mapper/features/map-layout/USSearchMapLayout.js
  covid-mapper/features/map-layout/USViewMapLayout.js
  covid-mapper/features/map-layout/WorldSearchMapLayout.js
  covid-mapper/features/map-layout/WorldViewMapLayout.js
  covid-mapper/features/map-layout/index.js
Labels: enhancement

#149 Rename drawer item labels
  covid-mapper/features/drawer/components/MainContent.js
Labels: enhancement

#150 Slider Open Button
  covid-mapper/commons/components/Icons/index.js
  covid-mapper/features/map-layout/USSearchMapLayout.js
  covid-mapper/features/map-layout/USViewMapLayout.js
  covid-mapper/features/map-layout/WorldSearchMapLayout.js
  covid-mapper/features/map-layout/WorldViewMapLayout.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSlider.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderButton.js
  covid-mapper/features/map-layout/components/popup-slider/index.js
Labels: enhancement

#153 Refactor WorldSearchMapView to fix country/province placeholder issue
  covid-mapper/features/map-layout/WorldSearchMapLayout.js
Labels: enhancement

#155 Refactor markers and initial region
  covid-mapper/features/map-layout/WorldSearchMapLayout.js
  covid-mapper/features/map/Map.js
Labels: enhancement

#156 Fixed the API error when APIs are fetched and fixed Searchbar input to not proceed any further if there are errors
  covid-mapper/commons/components/ErrorModal/ErrorModal.js
  covid-mapper/commons/components/ErrorModal/styles.js
  covid-mapper/features/map-layout/USSearchMapLayout.js
  covid-mapper/features/map-layout/USViewMapLayout.js
  covid-mapper/features/map-layout/WorldSearchMapLayout.js
  covid-mapper/features/map-layout/WorldViewMapLayout.js
Labels: enhancement

#157 Set county coordinate marker on Map
  covid-mapper/api/covidApi.js
  covid-mapper/features/map-layout/USSearchMapLayout.js
Labels: enhancement

#159 Fixed the loading Spinner when APIs are being fetched
  covid-mapper/features/map-layout/USSearchMapLayout.js
  covid-mapper/features/map-layout/USViewMapLayout.js
  covid-mapper/features/map-layout/WorldSearchMapLayout.js
  covid-mapper/features/map-layout/WorldViewMapLayout.js
  covid-mapper/features/searchbar/Searchbar.js
Labels: bug

#161 Displayed the Vaccine endpoints in the MapLayout
  covid-mapper/api/covidApi.js
  covid-mapper/features/drawer/DrawerMenu.js
  covid-mapper/features/map-layout/VaccineUSSearchMapLayout.js
  covid-mapper/features/map-layout/VaccineUSViewMapLayout.js
  covid-mapper/features/map-layout/VaccineWorldSearchMapLayout.js
  covid-mapper/features/map-layout/VaccineWorldViewMapLayout.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSlider.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js
  covid-mapper/features/map-layout/index.js
Labels: enhancement

#164 Infinite Scoll Simulator
  covid-mapper/features/map-layout/components/popup-slider/PopupSlider.js
  covid-mapper/package-lock.json
  covid-mapper/package.json
  covid-mapper/utils/index.js
  covid-mapper/utils/loadMore.js
  covid-mapper/yarn.lock
Labels: enhancement

#167 Finish About page
  covid-mapper/commons/components/Icons/index.js
  covid-mapper/features/about/About.js
  covid-mapper/features/about/component/AboutSection.js
  covid-mapper/utils/teamData.js
Labels: enhancement

#168 Split `PopupSlider` component with slot pattern
  covid-mapper/features/map-layout/USSearchMapLayout.js
  covid-mapper/features/map-layout/USViewMapLayout.js
  covid-mapper/features/map-layout/VaccineUSSearchMapLayout.js
  covid-mapper/features/map-layout/VaccineUSViewMapLayout.js
  covid-mapper/features/map-layout/VaccineWorldSearchMapLayout.js
  covid-mapper/features/map-layout/VaccineWorldViewMapLayout.js
  covid-mapper/features/map-layout/WorldSearchMapLayout.js
  covid-mapper/features/map-layout/WorldViewMapLayout.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSlider.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderArray.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderObject.js
  covid-mapper/features/map-layout/components/popup-slider/index.js
Labels: enhancement

#169 Add README - part 1
  covid-mapper/README.md
Labels: documentation, enhancement

#172 Trim whitespaces
  covid-mapper/features/map-layout/MapLayout.js
  covid-mapper/features/map-layout/USSearchMapLayout.js
  covid-mapper/features/map-layout/WorldSearchMapLayout.js
Labels: enhancement

#178 Refactor vaccine components to speed up rendering
  covid-mapper/features/vaccine-layout/VaccineLayout.js
  covid-mapper/features/vaccine-layout/components/VaccineItem.js
Labels: bug, enhancement

#181 Add more data to line chart
  covid-mapper/features/graphs/TimeLineGraph.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js
Labels: enhancement

#184 Change keyboard layout mode to 'pan'
  covid-mapper/app.json
Labels: enhancement

#186 Adjust covidApi, conditional render, and null checks
  covid-mapper/api/covidApi.js
  covid-mapper/features/graphs/TimeLineGraph.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderArray.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderObject.js
Labels: bug, enhancement

#188 Clean up
  covid-mapper/features/drawer/DrawerMenu.js
  covid-mapper/features/map-layout/MapLayout.js
  covid-mapper/features/map-layout/USSearchMapLayout.js
  covid-mapper/features/map-layout/USViewMapLayout.js
  covid-mapper/features/map-layout/VaccineUSSearchMapLayout.js
  covid-mapper/features/map-layout/VaccineUSViewMapLayout.js
  covid-mapper/features/map-layout/VaccineWorldSearchMapLayout.js
  covid-mapper/features/map-layout/VaccineWorldViewMapLayout.js
  covid-mapper/features/map-layout/WorldSearchMapLayout.js
  covid-mapper/features/map-layout/WorldViewMapLayout.js
Labels: enhancement

#190 Some stylings for the data in PopupSlider
  covid-mapper/features/map-layout/components/popup-slider/PopupSlider.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js
Labels: enhancement

#192 Modify graph label rotation angle and styling
  covid-mapper/features/graphs/TimeLineGraph.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js
Labels: enhancement

#193 Progress Graph Chart
  covid-mapper/api/covidApi.js
  covid-mapper/features/graphs/OverviewGraph.js
  covid-mapper/features/graphs/index.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js
Labels: bug, enhancement

#196 eas publish configuration
  covid-mapper/app.json
  covid-mapper/eas.json
  covid-mapper/package-lock.json
  covid-mapper/yarn.lock
Labels: enhancement

#201 Fixed UX bug: Changed ordering of the graph data
  covid-mapper/features/graphs/OverviewGraph.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js
Labels: bug

#203 chore(version-bump): bump version
  covid-mapper/app.json
  covid-mapper/package.json
Labels: enhancement

#206 Acceptance test file for QA team
  ACCEPTANCE.md
Labels: qa test

#210 Changed the initial region of the map based on the navigation route
  covid-mapper/features/map-layout/USSearchMapLayout.js
  covid-mapper/features/map-layout/USViewMapLayout.js
  covid-mapper/features/map-layout/VaccineUSSearchMapLayout.js
  covid-mapper/features/map-layout/VaccineUSViewMapLayout.js
  covid-mapper/features/map-layout/VaccineWorldSearchMapLayout.js
  covid-mapper/features/map-layout/VaccineWorldViewMapLayout.js
  covid-mapper/features/map-layout/WorldSearchMapLayout.js
  covid-mapper/features/map-layout/WorldViewMapLayout.js
Labels: bug

#214 Increase font weight for data
  covid-mapper/features/graphs/TimeLineGraph.js
  covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js
Labels: enhancement

#215 Fixed user location permission errors
  covid-mapper/features/map-layout/USSearchMapLayout.js
  covid-mapper/features/map-layout/USViewMapLayout.js
  covid-mapper/features/map-layout/VaccineUSSearchMapLayout.js
  covid-mapper/features/map-layout/VaccineUSViewMapLayout.js
  covid-mapper/features/map-layout/VaccineWorldSearchMapLayout.js
  covid-mapper/features/map-layout/VaccineWorldViewMapLayout.js
  covid-mapper/features/map-layout/WorldSearchMapLayout.js
  covid-mapper/features/map-layout/WorldViewMapLayout.js
Labels: bug
